// Generated by CoffeeScript 1.3.3
(function() {

  module.exports.string = function(size) {
    var chars, random, s, _i;
    chars = "abcdefghiklmnopqrstuvwxyz1234567890ABCDEFGHIKLMNOPQRSTUVWXYZ";
    random = "";
    if (size >= 100) {
      size = 100;
    }
    for (s = _i = 1; 1 <= size ? _i <= size : _i >= size; s = 1 <= size ? ++_i : --_i) {
      this.rnum = Math.floor(Math.random() * chars.length);
      random += chars.substring(this.rnum, this.rnum + 1);
    }
    return random;
  };

  module.exports.number = function(from, to) {
    var i, j, shuffle, tempi, tempj, _i, _j, _k, _len, _results, _results1;
    shuffle = [];
    if (to === void 0) {
      shuffle = (function() {
        _results = [];
        for (var _i = 0; 0 <= from ? _i <= from : _i >= from; 0 <= from ? _i++ : _i--){ _results.push(_i); }
        return _results;
      }).apply(this);
    } else {
      shuffle = (function() {
        _results1 = [];
        for (var _j = from; from <= to ? _j <= to : _j >= to; from <= to ? _j++ : _j--){ _results1.push(_j); }
        return _results1;
      }).apply(this);
    }
    for (_k = 0, _len = shuffle.length; _k < _len; _k++) {
      i = shuffle[_k];
      j = Math.floor(Math.random() * (i + 1));
      tempi = shuffle[i];
      tempj = shuffle[j];
      shuffle[i] = tempj;
      shuffle[j] = tempi;
    }
    return shuffle[0];
  };

}).call(this);
