// Generated by CoffeeScript 1.3.3
(function() {
  var client, irc, settings;

  irc = require("irc");

  settings = {
    server: "irc.prison.net",
    channel: "#dreamincode",
    nick: "Vapor"
  };

  client = new irc.Client(settings.server, settings.nick, {
    channels: [settings.channel],
    debug: true
  });

  client.addListener("connect", function() {
    return client.say(settings.channel, "Hello, I'm just another bot! :P");
  });

  client.addListener("message" + settings.channel, function(nick, msg) {
    return console.log("<" + nick + "> " + msg);
  });

  client.addListener("pm", function(from, msg) {
    return console.log("PM <" + from + "> " + msg);
  });

}).call(this);
